'use client';

import React, { useState } from 'react';
import {
  X,
  Download,
  Printer,
  Copy,
  Check,
  Sparkles,
  ShieldCheck
} from 'lucide-react';
import { DocumentAnalysis } from '@/lib/types';

interface ExportModalProps {
  doc: DocumentAnalysis;
  isOpen: boolean;
  onClose: () => void;
}

export default function ExportModal({ doc, isOpen, onClose }: ExportModalProps) {
  const [copied, setCopied] = useState(false);

  if (!isOpen) return null;

  const markdownContent = `# Agent One Executive Document Audit Memo
**Document:** ${doc.name}
**Pages:** ${doc.pageCount} pages | **Status:** Verified
**Audited At:** ${doc.uploadedAt}

---

## 1. Executive Summary
${doc.summary.tldr}

## 2. Key Findings & Extracted Takeaways
${doc.summary.keyTakeaways.map((k) => `- ${k}`).join('\n')}

## 3. Financial & Risk Metrics
${doc.metrics.map((m) => `- **${m.label}:** ${m.value} (${m.subtext || ''})`).join('\n')}

## 4. Priority Action Checklist
${doc.summary.actionChecklist.map((a) => `- [${a.completed ? 'x' : ' '}] **[${a.priority.toUpperCase()}]** ${a.text}`).join('\n')}

---
*Generated by Agent One — AI-Powered Document Intelligence & Insight Extraction*
`;

  const handleCopyMarkdown = () => {
    navigator.clipboard.writeText(markdownContent);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadMarkdown = () => {
    const blob = new Blob([markdownContent], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${doc.name.replace(/\.[^/.]+$/, '')}_AgentOne_Audit.md`;
    link.click();
    URL.revokeObjectURL(url);
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-2.5 sm:p-6 bg-black/65 backdrop-blur-2xl animate-in fade-in select-none">
      {/* Clickable backdrop */}
      <div
        className="fixed inset-0 cursor-pointer"
        onClick={onClose}
        aria-hidden="true"
      />

      {/* Liquid Glass Modal Window */}
      <div
        onClick={(e) => e.stopPropagation()}
        className="relative z-10 liquid-glass-modal rounded-[24px] sm:rounded-[32px] max-w-2xl w-full text-white overflow-hidden flex flex-col max-h-[92vh] sm:max-h-[88vh] animate-in zoom-in-95 duration-250 group"
      >
        {/* Ambient Fluid Glow */}
        <div className="absolute top-0 left-1/3 w-64 h-44 bg-blue-500/20 rounded-full blur-3xl pointer-events-none -z-10" />
        <div className="absolute bottom-0 right-1/3 w-64 h-44 bg-indigo-500/20 rounded-full blur-3xl pointer-events-none -z-10" />

        {/* Modal Header */}
        <div className="p-4 sm:p-6 px-4 sm:px-7 border-b border-white/[0.12] flex items-center justify-between bg-white/[0.02] flex-shrink-0">
          <div className="flex items-center gap-3 sm:gap-3.5 min-w-0 pr-2">
            <div className="w-9 h-9 sm:w-11 sm:h-11 rounded-2xl bg-gradient-to-tr from-blue-600/30 to-indigo-500/20 border border-white/20 flex items-center justify-center text-blue-300 shadow-[inset_0_1px_1px_rgba(255,255,255,0.4)] flex-shrink-0">
              <Sparkles className="w-4 h-4 sm:w-5 sm:h-5" />
            </div>
            <div className="min-w-0">
              <h3 className="text-sm sm:text-lg font-bold text-white tracking-tight truncate">
                Export Executive Memo
              </h3>
              <p className="text-[11px] sm:text-xs text-slate-300/80 mt-0.5 truncate">
                Verified audit of <span className="text-blue-300 font-semibold">{doc.name}</span>
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="w-8 h-8 sm:w-9 sm:h-9 rounded-full bg-white/5 hover:bg-white/15 border border-white/10 flex items-center justify-center text-slate-300 hover:text-white transition-all cursor-pointer backdrop-blur-md hover:scale-105 flex-shrink-0 touch-target"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Memo Preview Box */}
        <div className="p-4 sm:p-6 overflow-y-auto bg-black/40 text-slate-200 text-xs font-mono whitespace-pre-wrap border-b border-white/[0.08] leading-relaxed max-h-80 sm:max-h-96 scrollbar-thin">
          {markdownContent}
        </div>

        {/* Actions Footer */}
        <div className="p-4 sm:p-5 px-4 sm:px-7 border-t border-white/[0.12] bg-white/[0.02] backdrop-blur-2xl flex flex-col sm:flex-row items-stretch sm:items-center justify-between gap-3 flex-shrink-0">
          <span className="text-[11px] sm:text-xs text-slate-300/80 flex items-center gap-1.5 font-mono justify-center sm:justify-start">
            <ShieldCheck className="w-4 h-4 text-emerald-400 flex-shrink-0" />
            Agent One Verified Audit Signature
          </span>

          <div className="flex flex-wrap items-center gap-2">
            <button
              onClick={handleCopyMarkdown}
              className="flex-1 sm:flex-initial flex items-center justify-center gap-1.5 px-3.5 py-2 rounded-full text-xs font-semibold bg-white/5 hover:bg-white/15 border border-white/10 text-white transition-all cursor-pointer touch-target"
            >
              {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
              <span>{copied ? 'Copied!' : 'Copy'}</span>
            </button>

            <button
              onClick={handlePrint}
              className="flex-1 sm:flex-initial flex items-center justify-center gap-1.5 px-3.5 py-2 rounded-full text-xs font-semibold bg-white/5 hover:bg-white/15 border border-white/10 text-white transition-all cursor-pointer touch-target"
            >
              <Printer className="w-3.5 h-3.5" />
              <span>Print</span>
            </button>

            <button
              onClick={handleDownloadMarkdown}
              className="w-full sm:w-auto liquid-glass-button flex items-center justify-center gap-1.5 px-5 py-2 rounded-full text-xs font-bold text-white transition-all cursor-pointer hover:scale-105 active:scale-95 touch-target"
            >
              <Download className="w-3.5 h-3.5 text-white" />
              <span>Download .md</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
